### PR TITLE
support barcode encoded fedex smartpost value

### PR DESCRIPTION
**Pull request by sholomke**
when scanning fedex smartpost packages i get values like:
420 11213 92 6129098349792366623 8 (RoutingApplicationId, DestinationZip, ApplicationIdentifier, SerialNumber, CheckDigit).
the current regex only handles:
92 6129098349792366623 8, or 6129098349792366623 8.
the updated regex handles:
420 11213 92 6129098349792366623 8: pass (new)
92 6129098349792366623 8: pass (same as before)
6129098349792366623 8: pass (same as before)
420 11213 6129098349792366623 8: fail (same as before)
420 92 6129098349792366623 8: fail (same as before)
11213 92 6129098349792366623 8: fail (same as before)

### CODE REVIEW

**Comment by jkeen** [comment]
This is great @sholomke, thanks for the PR. Can you add a test for the new number format? Seems like the other tests are passing, but it'd be good to have one for this new change.

**Comment by jkeen** [comment]
Wait wait I take that back, I guess there's no tests for specific numbers in this repo. I don't even know my own code

**Comment by sholomke** [comment]
Thanks for the kind words.
Will add in a bit.
Thanks for the great repo.

**Comment by sholomke** [comment]
Oops ok.

**Comment by sholomke** [comment]
Right this is just the json’s…

**Comment by jkeen** [comment]
Yeah, what would would be great is if the github action downloaded the latest copy of the ruby `tracking-number` gem, put the new data in `/lib/data` and ran *those* tests. I'm not sure if I'll have time to get to that today, but that's what probably needs to happen

**Pull request merged**
